name: Eco_SmartRoom
description: "Aplicativo para visualizar relatórios de plantas e baterias"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^30.2.7
  flutter_local_notifications: ^19.4.1
  firebase_messaging: ^16.0.1
  provider: ^6.1.5+1
  firebase_core: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/title.png
